name: shellcheck

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Install latest shfmt
        run: GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt

      - name: Run shfmt and shellcheck
        run: |
          ./.github/run-lint.sh
