name: shellspec

on:
  workflow_dispatch:
  pull_request:

jobs:
  unit_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Add path
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install latest shellspec
        run: wget -O- https://git.io/shellspec | sh -s -- --yes

      - name: Run shellspec
        run: |
          ./.github/run-test.sh
